version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment: 
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
      
  chrome:
    image: selenium/node-chrome-debug:3.141.59-oxygen
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=2
      - NODE_MAX_INSTANCES=2
    ports:
      - "5555"
      - "5900:5900"

  # firefox:
  #   image: selenium/node-firefox:3.141.59-zirconium
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
